// Evite remover categorias existentes, apenas adicionar caso necessário
export const defaultProductCategories = [
  'Calças',
  'Camisetas',
  'Shorts',
  'Saias',
  'Vestidos',
  'Blusas',
  'Bebês',
  'Jeans',
  'Acessórios',
  'Beleza',
  'Calçados',
  'Casa',
  'Casual',
  'Evangélica',
  'Fitness',
  'Infantil',
  'Íntima',
  'Plus Size',
  'Praia',
  'Sleepwear',
  'Social',
  'Outros',
]
