
export default {
  ALREADY_IN_USE: 'ALREADY_IN_USE',
  TOO_SHORT: 'TOO_SHORT',
  TOO_BIG: 'TOO_BIG',
  INVALID: 'INVALID',
  MISSING: 'MISSING',
  MISSING_SELLING_LOCATION: 'MISSING_SELLING_LOCATION',
  UNAUTHORIZED: 'UNAUTHORIZED',
  LOCATION_OCCUPIED: 'LOCATION_OCCUPIED',
};